CC=c++
CFLAGS=-g -O0 -std=c++14

all:  q1 q2 q3 q4 q5

q1: q1.cpp
	$(CC) $(CFLAGS) $< -o $@
q2: q2.cpp
	$(CC) $(CFLAGS) $< -o $@
q3: q3.cpp
	$(CC) $(CFLAGS) $< -o $@
q4: q4.cpp
	$(CC) $(CFLAGS) $< -o $@
q5: q5.cpp
	$(CC) $(CFLAGS) $< -o $@
clean:
	@echo "Cleanup..." 
	rm -rf *.o *~

